INHERIT: ../../mkdocs.base.yml
site_name: omni_httpd
nav:
- Installation: 'install.md'
- Intro: 'intro.md'
- Headers: 'headers.md'
- Architecture: 'architecture.md'
- Security: 'security.md'
- Reverse Proxy: 'reverse_proxy.md'
- Routing: 'routing.md'
- Static File Server: 'static_file.md'
