#!/usr/bin/env bash

set -eux

cat </build/artifacts.txt | while IFS= read -r line; do
    pkg="$(echo "$line"|awk -F'=' '{print $1}')"
    vers="$(echo "$line"|cut -d'#' -f1|awk -F'=' '{print $2}')"
    deps="--depends postgresql-$POSTGRES_VER"
    for d in $(echo "$line"|awk -F'#' '{print $2}'|tr ',' ' ') ; do
        n="$(echo "$d"|awk -F'=' '{print $1}')"
        v="$(echo "$d"|awk -F'=' '{print $2}')"
        case $n in \
            dblink|pgcrypto)
                n="postgresql-contrib-$POSTGRES_VER" ; v='*' ;;
            plpy*)
                n="postgresql-plpython3-$POSTGRES_VER" ; v='*' ;;
        esac
        if [ "$v" = "*" ]; then
            deps="$deps --depends '$n'"
        else
            deps="$deps --depends '$n >= $v'"
        fi
    done
    tmp="$(mktemp -d)"
    mkdir -p "$tmp/lib/postgresql/$POSTGRES_VER/lib"
    mkdir -p "$tmp/share/postgresql/$POSTGRES_VER/extension"
    cp "/build/packaged/$pkg"--*.so        "$tmp/lib/postgresql/$POSTGRES_VER/lib" && arch=native || arch=all
    cp "/build/packaged/extension/$pkg".*  "$tmp/share/postgresql/$POSTGRES_VER/extension" || true
    cp "/build/packaged/extension/$pkg"--* "$tmp/share/postgresql/$POSTGRES_VER/extension" || true
    eval "${GEM_HOME}/bin/fpm" \
         --input-type dir \
         --output-type deb \
         --architecture "$arch" \
         --name "$pkg" \
         --version "$vers" \
         --iteration "$ITERATION" \
         --prefix /usr \
         --chdir "$tmp" \
         "$deps" \
         .
done
