/*{%
  set meta_views = ["schema",
                    "cast","cast_binary_coercible","cast_function","cast_implicit","cast_implicit_in_assignment","cast_explicit",
                    "operator",
                    "sequence", "sequence_minimum_value", "sequence_start_value", "sequence_maximum_value",
                                "sequence_cycle", "sequence_increment", "sequence_type", "sequence_cache",
                                "sequence_table",
                    "relation_column","relation_column_type","relation_column_position","relation_column_default",
                                      "relation_column_identity", "relation_column_generated",
                                      "relation_column_nullable","relation",
                    "table","table_permanent", "table_temporary", "table_partitioned", "table_rowsecurity", "table_forcerowsecurity",
                    "view",
                    "callable", "callable_function", "callable_procedure", "callable_return_type", "callable_owner",
                                "callable_argument_name", "callable_argument_type", "callable_argument_mode", "callable_argument_default",
                                "callable_immutable", "callable_volatile", "callable_stable",
                                "callable_aggregate", "callable_window",
                                "callable_parallel_safe", "callable_parallel_unsafe", "callable_parallel_restricted",
                                "callable_security_definer", "callable_security_invoker","callable_language",
                                "callable_acl", "callable_body",
                    "trigger",
                    "role", "role_superuser", "role_inherit", "role_create_role", "role_create_db",
                            "role_can_login", "role_replication", "role_connection_limit",
                            "role_valid_until", "role_setting",
                    "policy","policy_role",
                    "constraint_relation_non_null","constraint_relation_non_null_column",
                    "constraint_relation_check", "constraint_relation_check_expr",
                    "constraint_relation_unique","constraint_relation_unique_column",
                    "extension",
                    "foreign_data_wrapper","foreign_server","foreign_table","foreign_column",
                    "relation_foreign_key", "relation_foreign_key_constraint", "constraint_relation_foreign_key",
                         "constraint_relation_foreign_key_update", "constraint_relation_foreign_key_delete",
                         "constraint_relation_foreign_key_match_full", "constraint_relation_foreign_key_match_partial",
                         "constraint_relation_foreign_key_match_simple", "constraint_relation_foreign_key_references",
                         "constraint_relation_foreign_key_references_column",
                    "type", "type_basic", "type_array", "type_composite","type_composite_attribute",
                            "type_composite_attribute_position","type_composite_attribute_collation",
                            "type_domain","type_enum","type_enum_label", "type_pseudo", "type_range","type_multirange",
                    "index","index_relation", "index_unique", "index_unique_null_values_distinct",
                            "index_primary_key", "index_unique_immediate", "index_replica_identity",
                            "index_attribute","index_partial",
                    "language", "language_internal", "language_trusted", "language_handler", "language_inline_handler",
                                "language_validator", "language_acl",
                    "comment", "dependency",
                    "acl"
                    ]
 %}*/

/*{% block content %}*/
/*{% endblock %}*/
