file(READ "${CMAKE_CURRENT_LIST_DIR}/../../deps/dependencies.txt" deps)
string(REPLACE "\n" ";" deps "${deps}")
separate_arguments(deps)

foreach (dep ${deps})
    string(REPLACE "=" ";" key_value ${dep})
    list(GET key_value 0 name)
    list(GET key_value 1 value)

    string(REPLACE "@" ";" value_parts ${value})
    separate_arguments(value_parts)
    list(GET value_parts 0 repo)
    list(GET value_parts 1 ver)
    set("VERSION_${name}" "${ver}")
endforeach ()