[project]
name = "omni_python"
version = "0.1.0"
authors = [
    { name="Yurii Rashkovskii", email="yrashk@gmail.com" },
]
description = "Omnigres integration package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Database"
]
