macro(add_subdirectory_once)
    if(${ARGC} GREATER 0)
        set(_subdir_DIR ${ARGV0})
        if(${ARGC} GREATER 1)
            set(_subdir_BINARY_DIR ${ARGV1})
        endif()
        file(REAL_PATH ${_subdir_DIR} _add_subdirectory_once_dir)
        if(NOT DEFINED ENV{"subdirectory_${_add_subdirectory_once_dir}"})
            set(ENV{"subdirectory_${_add_subdirectory_once_dir}"} ON)
            add_subdirectory(${_subdir_DIR} ${_subdir_BINARY_DIR})
        endif()
    endif()
endmacro()