include(CPM)
include(CheckCSourceCompiles)
include(FindPkgConfig)

pkg_check_modules (H2O libh2o-evloop)

cmake_policy(SET CMP0042 NEW)
if (NOT H2O_FOUND)
  set(_h2o_options)
  list(APPEND _h2o_options "WITH_MRUBY OFF")
  list(APPEND _h2o_options "DISABLE_LIBUV ON")
  CPMAddPackage(NAME h2o GIT_REPOSITORY https://github.com/h2o/h2o GIT_TAG 579135a VERSION 2.3.0-579135a OPTIONS "${_h2o_options}")
  set(H2O_LIBRARIES libh2o-evloop)
  set_property(TARGET libh2o-evloop PROPERTY POSITION_INDEPENDENT_CODE ON)
endif()
