set_property(GLOBAL PROPERTY version_dir "${CMAKE_CURRENT_LIST_DIR}")

macro(get_version NAME VERSION_VAR)

    string(TOUPPER ${NAME} _name)

    if(DEFINED ${_name}_VERSION)
        set("${VERSION_VAR}" "${${_name}_VERSION}")
    elseif(DEFINED OMNIGRES_VERSION)
        set("${VERSION_VAR}" "${OMNIGRES_VERSION}")
    else()
        get_property(dir GLOBAL PROPERTY version_dir)
        string(STRIP "${VERSION_VAR}" VERSION_VAR)

        file(STRINGS ${dir}/../versions.txt lines)
        set(seen_extensions "")
        set(line_regex "^[a-z0-9_]+=[0-9]+\\.[0-9]+\\.[0-9]+")
        foreach(line ${lines})
            string(REGEX MATCH ${line_regex}  line_match ${line})
            if(NOT "${line_match}" STREQUAL ${line})
                message(FATAL_ERROR "\"${line}\" does not match with regex \"${line_regex}\" in ${dir}/../versions.txt")
            endif()
            string(FIND ${line} "=" line_name_length)
            string(SUBSTRING ${line} 0 ${line_name_length} line_name)
            if("${line_name}" IN_LIST seen_extensions)
                message(FATAL_ERROR "\"${line_name}\" found more than once in ${dir}/../versions.txt")
            endif()
            list(APPEND seen_extensions ${line_name})
            MATH(EXPR line_version_index "${line_name_length}+1")
            string(SUBSTRING ${line} ${line_version_index} -1 line_version)
            if("${line_name}" STREQUAL ${NAME})
                set("${VERSION_VAR}" "${line_version}")
            endif()
        endforeach()
        if(NOT "${NAME}" IN_LIST seen_extensions)
            set("${VERSION_VAR}" unreleased)
        endif()
    endif()

    unset(_name)

endmacro()

function(set_version NAME VERSION)
    get_property(dir GLOBAL PROPERTY version_dir)
    file(READ "${dir}/../versions.txt" _file_contents)
    # Replace ${NAME}=... with ${NAME}=${VERSION}
    string(REGEX REPLACE "${NAME}=[^\n]*" "${NAME}=${VERSION}" _file_contents "${_file_contents}")
    file(WRITE "${dir}/../versions.txt" "${_file_contents}")
endfunction()
